server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event_manager
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update